### ISSUE TITLE
Repeated error messages

### ISSUE THREAD

**Issue by AaronBenDaniel** [TheOnlyWayUp/WattpadDownloader#22]
(Probably a caching issue, but not confirmed)

Users have reported receiving error messages when attempting to download stories. The issue is inconsistent and does not always happen. So far the error messages I've personally confirmed (for stories that definitely exist) include:

- Internal server error (completely unhandled exception)
- ClientResponseError 429 (Rate-limit by Wattpad)
- ClientResponseError 400|404 (This story does not exist)

Relevant logs:
```
INFO:     10.0.1.182:52690 - "GET /download/314175600?om=1&download_images=true&mode=story HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 116, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 746, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 55, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 44, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 70, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 103, in handle_download
    async for title in add_chapters(
  File "/app/create_book.py", line 215, in add_chapters
    async with session.get(image["src"]) as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp_client_cache/session.py", line 51, in _request
    response, actions = await self.cache.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 139, in request
    response = None if actions.skip_read else await self.get_response(actions.key)
  File "/usr/local/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 147, in get_response
    response = await self.responses.read(key) or await self._get_redirect_response(str(key))
  File "/usr/local/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 169, in _get_redirect_response
    redirect_key = await self.redirects.read(key)
  File "/usr/local/lib/python3.10/site-packages/aiohttp_client_cache/backends/sqlite.py", line 180, in read
    row = await cursor.fetchone()
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/cursor.py", line 65, in fetchone
    return await self._execute(self._cursor.fetchone)
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by TheOnlyWayUp** [comment]
I can reproduce this error,
```py
import asyncio
import aiohttp
from rich import print


PORT: int = 8086
DOWNLOAD_URL = (
    f"http://localhost:{PORT}/download/314175600?om=1&download_images=true&mode=story"
)


async def fetch(task_id: int, session: aiohttp.ClientSession):
    print("started", task_id)
    async with session.get(DOWNLOAD_URL) as response:
        print(task_id, response.status)


async def main():
    session = aiohttp.ClientSession()

    await asyncio.gather(*[fetch(i, session) for i in range(30)])


if __name__ == "__main__":
    asyncio.run(main())
```

Error:
```
INFO:     127.0.0.1:47646 - "GET /download/314175600?om=1&download_images=true&mode=story HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/src/main.py", line 101, in handle_download
    await set_cover(book, metadata, cookies=cookies)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/src/create_book.py", line 218, in set_cover
    book.set_cover("cover.jpg", await fetch_cover(data["cover"], cookies=cookies))
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/src/create_book.py", line 186, in fetch_cover
    async with session.get(url) as response:
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiohttp_client_cache/session.py", line 51, in _request
    response, actions = await self.cache.request(
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 139, in request
    response = None if actions.skip_read else await self.get_response(actions.key)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 147, in get_response
    response = await self.responses.read(key) or await self._get_redirect_response(str(key))
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiohttp_client_cache/backends/base.py", line 169, in _get_redirect_response
    redirect_key = await self.redirects.read(key)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiohttp_client_cache/backends/sqlite.py", line 180, in read
    row = await cursor.fetchone()
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiosqlite/cursor.py", line 65, in fetchone
    return await self._execute(self._cursor.fetchone)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiosqlite/cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/home/thel/code/projects/personal/WattpadDownloader/src/api/.venv/lib/python3.10/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

Not a single request was successful. As soon as requests become concurrent, the database gives out and all connections fail.

The cache is important, it holds onto popular books and prevents hammering Wattpad for data we can store. Proposed fix is to add support for Redis as a cache.
