### ISSUE TITLE
PDF Downloads

### ISSUE THREAD

**Issue by TheOnlyWayUp** [TheOnlyWayUp/WattpadDownloader#29]
PDF Downloads would be great.

References:
- [Archive-WP/WattpadScrape - scrape.py](https://github.com/Archive-WP/WattpadScraper/blob/master/scraper/wattpad_scraper/scrape.py)

This feature will be available to donators in December 2024.

Scheduled to release in January 2025, early release is bountied at $50.

Want to support development, and get early-access to features?
- [Buy me a coffee](https://buymeacoffee.com/theonlywayup) or [Sponsor me on Github or Patreon](https://github.com/sponsors/TheOnlyWayUp)

**Comment by TheOnlyWayUp** [comment]
016ad6209affc357b8185e7a45e1602c820eb84a (private) implements PDF Downloads with `wkhtmltopdf` and `pdfkit`. It took a lot of time and effort, and it works well.

Unfortunately, `wkhtmltopdf` is EOL and is riddled with vulnerabilities - it's a great library for rendering trusted HTML, but that's not applicable here. Also, I can't help but feel excited looking at Weasyprint's samples lol - [Preview Book.pdf](https://github.com/CourtBouillon/weasyprint-samples/blob/main/book/book.pdf).

Relevant: [wkhtmltopdf recommendations](https://wkhtmltopdf.org/status.html#recommendations)

**Comment by AaronBenDaniel** [comment]
As of writing this, the Dockerfile in `feature/#29-pdf-downloads` is broken. The container builds with a missing library that results in the following output when being run.

```

-----

WeasyPrint could not import some external libraries. Please carefully follow the installation steps before reporting an issue:
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation
https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting 

-----

Traceback (most recent call last):
  File "/app/src/main.py", line 18, in <module>
    from create_book import (
  File "/app/src/create_book.py", line 14, in <module>
    from weasyprint import HTML, CSS, default_url_fetcher
  File "/usr/local/lib/python3.10/site-packages/weasyprint/__init__.py", line 425, in <module>
    from .css import preprocess_stylesheet  # noqa: I001, E402
  File "/usr/local/lib/python3.10/site-packages/weasyprint/css/__init__.py", line 28, in <module>
    from .computed_values import COMPUTER_FUNCTIONS
  File "/usr/local/lib/python3.10/site-packages/weasyprint/css/computed_values.py", line 9, in <module>
    from ..text.ffi import FROM_UNITS, ffi, pango
  File "/usr/local/lib/python3.10/site-packages/weasyprint/text/ffi.py", line 447, in <module>
    pango = _dlopen(
  File "/usr/local/lib/python3.10/site-packages/weasyprint/text/ffi.py", line 432, in _dlopen
    return ffi.dlopen(names[0], flags)  # pragma: no cover
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 834, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.10/site-packages/cffi/api.py", line 829, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libpango-1.0-0': libpango-1.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libpango-1.0-0'
```

**Comment by AaronBenDaniel** [comment]
See #33 for proposed fix

**Comment by TheOnlyWayUp** [comment]
I'm figuring out ways to improve the speed of PDF downloads, we can roll out the feature to everyone when it's performant.
